pipeline {
    agent any
    stages {
        stage('Compile') {
            steps {
                dir('Chapter08/sample1') {
                    sh 'chmod +x gradlew'
                    sh './gradlew compileJava'
                }
            }
        }
        stage('Unit test') {
            steps {
                dir('Chapter08/sample1') {
                    sh './gradlew test'
                }
            }
        }
        stage('Code coverage') {
            steps {
                dir('Chapter08/sample1') {
                    sh './gradlew jacocoTestReport'
                    sh './gradlew jacocoTestCoverageVerification'
                }
            }
        }
    }
}