pipeline {
    agent any
    stages {
        stage('Compile') {
            steps {
                dir('Chapter08/sample1') {
                    sh 'bash gradlew compileJava'
                }
            }
        }
        stage('Unit test') {
            steps {
                dir('Chapter08/sample1') {
                    sh 'bash gradlew test'
                }
            }
        }
        stage('Code coverage') {
            steps {
                dir('Chapter08/sample1') {
                    sh 'bash gradlew jacocoTestReport'
                    sh 'bash gradlew jacocoTestCoverageVerification'
                }
            }
        }
    }
}