pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Unit Test') {
            steps {
                dir('Chapter08/sample1') {
                    sh 'bash gradlew test'
                }
            }
        }
        stage('Code Coverage') {
            when {
                branch 'main'
            }
            steps {
                dir('Chapter08/sample1') {
                    sh 'bash gradlew jacocoTestReport'
                    sh 'bash gradlew jacocoTestCoverageVerification'
                }
            }
        }
        stage('Feature Branch Tests') {
            when {
                expression { env.BRANCH_NAME ==~ /.*feature.*/ }
            }
            steps {
                echo "Feature branch detected: ${env.BRANCH_NAME}"
                dir('Chapter08/sample1') {
                    sh 'bash gradlew test'
                }
            }
        }
        stage('Validate Branch') {
            when {
                expression {
                    !(env.BRANCH_NAME == 'main' || env.BRANCH_NAME ==~ /.*feature.*/)
                }
            }
            steps {
                error("Branch '${env.BRANCH_NAME}' is not allowed. Only 'main' and feature branches are permitted.")
            }
        }
    }
}